"""Adiciona data_tabulacao ao Lead

Revision ID: 328674710c8a
Revises: df9695c14cb2
Create Date: 2025-07-02 15:01:00.658812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328674710c8a'
down_revision = 'df9695c14cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_tabulacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('data_tabulacao')

    # ### end Alembic commands ###
