"""Criação inicial de todas as tabelas

Revision ID: de3b5f8f4eee
Revises: 
Create Date: 2025-07-02 14:06:30.671125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b5f8f4eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('situacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tabulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tipo_de_operacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=140), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('produto', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('tabulation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tabulation_id'], ['tabulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_data_criacao'), ['data_criacao'], unique=False)

    op.create_table('lead_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_proposta', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('banco_id', sa.Integer(), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('situacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo_operacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['banco.id'], ),
    sa.ForeignKeyConstraint(['consultor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenio.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['situacao_id'], ['situacao.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacao_id'], ['tipo_de_operacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposta_data_proposta'), ['data_proposta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposta_data_proposta'))

    op.drop_table('proposta')
    op.drop_table('lead_consumption')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_data_criacao'))

    op.drop_table('lead')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('tipo_de_operacao')
    op.drop_table('tabulation')
    op.drop_table('situacao')
    op.drop_table('convenio')
    op.drop_table('banco')
    # ### end Alembic commands ###
