"""Adiciona campo color a Tabulation

Revision ID: df9695c14cb2
Revises: de3b5f8f4eee
Create Date: 2025-07-02 14:42:14.426248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9695c14cb2'
down_revision = 'de3b5f8f4eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
